### ISSUE TITLE
Having trouble with .each statement in postPreview Template

### ISSUE THREAD

**Issue by alexcode18** [alexcode18/common_core#1]
The code doesn't seem to understand what 'tags' is referring to. The rest of the model info is carried from the postPreviewView into the template, so I don't see why tags wouldn't be. That leads me to believe that the .each action is written improperly.

**Comment by alexcode18** [comment]
The code doesn't seem to understand what 'tags' is referring to. The rest of the model info is carried from the postPreviewView into the template, so I don't see why tags wouldn't be. That leads me to believe that the .each action is written improperly.

@htella @DrRobotmck @harimohanraj89

**Comment by htella** [comment]
What file is this in? Is your latest code pushed?

**Comment by alexcode18** [comment]
I just pushed again. It's in postPreview.hbs

**Comment by htella** [comment]
Ok checking

**Comment by htella** [comment]
You are trying to use underscore.js templating. But you are writing a HandleBars template. Check out the HandleBars documentation to see how to loop through something like this. 

Check this page and look for the `each` helper

**Comment by alexcode18** [comment]
Great! It's working now.
