### ISSUE TITLE
Get clicked tags to render associated tags

### ISSUE THREAD

**Issue by alexcode18** [alexcode18/common_core#2]
I'm having trouble figuring out how to sort through the information I'm getting back from the the tag button object. I know the 'this' contains posts, but I'm not sure how to reach them.

@harimohanraj89 @DrRobotmck @htella

**Comment by htella** [comment]
can you point me to the tag button object in you code?

**Comment by alexcode18** [comment]
The template for the tag is in listTag.hbs. Rendering the tag is in the TagsListView.

**Comment by htella** [comment]
Hmm, I need more context. What do you mean by `the information` where are you `getting this back`

**Comment by alexcode18** [comment]
I need to get the posts associated with it so I can update App.posts to just that collection.

**Comment by alexcode18** [comment]
I was planning to use the method getTagPosts()

**Comment by htella** [comment]
Still not clear. Im going to look at your code. I'm assuming you are trying to filter your collection to only have posts with that particular tag that was clicked on perhaps?

**Comment by htella** [comment]
So after looking at your code I think you are confused about the responsibilities of the CollectionView (tagListView) and the ModelView (tagView).

**Comment by htella** [comment]
But I'm not sure what problem your trying to tackle right now. Is it rendering all the tags. Or is it some sort of thing that should happen to posts when I interact with a tag in some way?

**Comment by alexcode18** [comment]
The tags are rendering, but when you click on them, they should reset the books list with only titles meeting that tag.

**Comment by htella** [comment]
Latest code pushed?

**Comment by alexcode18** [comment]
I'm cleaning up that db right now. Can I put the tag on hold for a bit?

**Comment by htella** [comment]
Yup, do what think what's right.

**Comment by htella** [comment]
what you think is right.

**Comment by htella** [comment]
But I'll say this, before tackling `resetting the books list with only titles meeting that tag.` I think you should refactor `tagListView` so it uses `tagView` to render the tag. This way solving the first problem will be easier.

**Comment by htella** [comment]
Let me know if you want to look at some old code from class together.
